export enum TestType {
    ACCESSIBILITY = "Accessibility",
    ACCEPTANCE = "Acceptance",
    BLACK_BOX = "Black box",
    END_TO_END = "End to end",
    FUNCTIONAL = "Functional",
    INTERACTIVE = "Interactive",
    INTEGRATION = "Integration",
    LOAD = "Load",
    NON_FUNCTIONAL = "Non functional",
    PERFORMANCE = "Performance",
    REGRESSION = "Regression",
    SANITY = "Sanity",
    SECURITY = "Security",
    SINGLE_USER_PERFORMANCE = "Single user performance",
    SMOKE = "Smoke",
    STRESS = "Stress",
    UNIT = "Unit",
    WHITE_BOX = "White-box",
}